/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ua.com.kl.cmathtutor.mo;

public class Math {
    public static int fact(int n) {
	return MathJNI.fact(n);
    }

}
